---
- name: "Install wanted packages"
  apt:
    name:
      - apt-transport-https
      - arptables
      - bash-completion
      - bridge-utils
      - ca-certificates
      - coreutils
      - curl
      - dnsutils
      - ebtables
      - file
      - gawk
      - git
      - gnupg
      - htop
      - iftop
      - ifstat
      - iputils-ping
      - iptables
      - jq
      - libsqlite3-dev
      - libffi-dev
      - libpython3-dev
      - libssl-dev
      - locales-all
      - lsb-release
      - lsof
      - lvm2
      - mdadm
      - minicom
      - mtr-tiny
      - netcat
      - net-tools
      - ntp
      - openssl
      - p7zip-full
      - pwgen
      - sqlite3
      - strace
      - sudo
      - sysstat
      - telnet
      - tcpdump
      - tmux
      - uuid-runtime
      - unzip
      - vim-nox
      - wget
      - zip
    state: latest
    update_cache: true
    cache_valid_time: 3600
  register: apt_res
  retries: 5
  until: apt_res is success
- name: "Remove unanted packages"
  apt:
    name:
      - cloud-init
      - ntpdate
    state: absent
- name: "Setup hostname"
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"
- name: "Setup hosts"
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
